title: Hacker News Digest - Syazaril Asyraf
author: Syazaril Asyraf
email: wan@syazarilasyraf.com
url: https://hn.syazarilasyraf.com
baseurl: ""
description: The personal Hacker News Digest of Syazaril Asyraf

permalink: /:year/:month/:day/:title.html

# Include data files
include:
  - _data

# Exclude files from processing
exclude:
  - digest_script.py
  - requirements.txt
  - readme.md

favicon: "logo.png"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
